=== tillig/xmltools/UnitTests/Resources/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="first"/>
				<xs:element name="second"/>
				<xs:element name="unlimited" maxOccurs="unbounded">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="nested" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="value" type="xs:int" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tillig/xmltools/UnitTests/Resources/Valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema.xsd">
	<first/>
	<second/>
	<unlimited/>
	<unlimited value="1"/>
	<unlimited value="2">
		<nested/>
	</unlimited>
	<unlimited value="3">text</unlimited>
</root>
